solana_servers:
- https://neon-solrpc-mb-lb-1.solana.p2p.org/RkyUZGCodi5ZXrtlkZwzuMxUA7E80PQYav74ZkqWH
- https://frequent-muddy-sunset.solana-mainnet.quiknode.pro/4bed7709ca42b7d720d824a56039682428eb4c75
